### ISSUE TITLE
Update required 

### ISSUE THREAD

**Issue by KimiaKy** [3DTune-In/3dti_AudioToolkit#19]
The test.app doesn't open and I get the notification that the software needs an update. I am trying to install it on a mac.

**Comment by lpicinali** [comment]
Hello! Can you please let us know your MacOS version?

**Comment by KimiaKy** [comment]
Hi! It’s MacOS Monterey 12.6.2 (21G320). 




















_____________________

Kimia Koochakzadeh-Yazdi 
Composer | Performer | Sound Artist 
www.kimiayazdi.com

**Comment by lpicinali** [comment]
Thanks! I've just tested it on Monterey 12.6.1 and it works all fine...
Can you confirm that you downloaded the last available version of the Test App?

https://github.com/3DTune-In/3dti_AudioToolkit/releases/download/M20221031/BiTA.V4.0.0.D20221031.Tk-v2.0.M20221031.MAC.dmg

And...if you experience the same again, could you please send us a screenshot?

**Comment by KimiaKy** [comment]
I tried the link you sent and gave me the same error — sending the screenshot here. 

Thank you for your help! 
Kimia 




















_____________________

Kimia Koochakzadeh-Yazdi 
Composer | Performer | Sound Artist 
www.kimiayazdi.com

**Comment by lpicinali** [comment]
Sorry, can't seem to be able to seee the attachment...

**Comment by KimiaKy** [comment]
I’m attaching it again — thanks! 
Kimia 






















_____________________

Kimia Koochakzadeh-Yazdi 
Composer | Performer | Sound Artist 
www.kimiayazdi.com

**Comment by lpicinali** [comment]
Sorry...I still can't see it - could you please send it via email to l.picinali@imperial.ac.uk?

**Comment by lmtanco** [comment]
Hi Kimia, 

We are not sure why you are experiencing this.

Can you please try the following (if you haven't already) and get back to us? 

1. Make sure you drag and drop the app onto your "**Applications**" folder
2. The first time you open it, rather than double clicking it, press your right button (or Control-left button), then choose "**Open**" from the context menu. It should warn you, but still ask you wether you want to open it and give you the chance to say 'yes'. 
3. If it still doesn't give you that option, open "System Preferences", then go to "Security & Privacy", then "General". Make sure the little lock in the "Security & Privacy" is open so you can make changes. (you need to have administrator privileges for this).  Leave this window open. 
4. Repeat step 2 above. A message should appear in the "Security & Privacy" window alerting you that an application you downloaded was blocked. However, it should give you the option to allow it to open next time. Please allow it! 
5. Try then to open it a last (and hopefully successful) time, using again the method in step 2. 

Let us know how it goes! 

Cheers, Luis.

**Comment by KimiaKy** [comment]
Hi Luis,


It works now! Thank you for your help!

For some reason, it wasn’t showing up in my Security & Privacy part before! It did now and I got to finally open it!

Thank you,
Kimia

_____________________

Kimia Koochakzadeh-Yazdi
Composer | Performer | Sound Artist
www.kimiayazdi.com<http://www.kimiayazdi.com>





On Feb 2, 2023, at 2:06 AM, Luis Molina-Tanco ***@***.******@***.***>> wrote:



Hi Kimia,

We are not sure why you are experiencing this.

Can you please try the following (if you haven't already) and get back to us?

  1.  Make sure you drag and drop the app onto your "Applications" folder
  2.  The first time you open it, rather than double clicking it, press your right button (or Control-left button), then choose "Open" from the context menu. It should warn you, but still ask you wether you want to open it and give you the chance to say 'yes'.
  3.  If it still doesn't give you that option, open "System Preferences", then go to "Security & Privacy", then "General". Make sure the little lock in the "Security & Privacy" is open so you can make changes. (you need to have administrator privileges for this). Leave this window open.
  4.  Repeat step 2 above. A message should appear in the "Security & Privacy" window alerting you that an application you downloaded was blocked. However, it should give you the option to allow it to open next time. Please allow it!
  5.  Try then to open it a last (and hopefully successful) time, using again the method in step 2.

Let us know how it goes!

Cheers, Luis.

**Comment by lmtanco** [comment]
Great! Thanks for letting us now!
