### ISSUE TITLE
compilation instructions

### ISSUE THREAD

**Issue by jhwang7628** [3DTune-In/3dti_AudioToolkit#4]
Does the toolkit come with compilation instructions/tools or are we expected to configure our own build systems?

**Comment by areyesl** [comment]
In order to be more platform independent, the 3D Tune-In Audiotoolkit is presented as a library for processing audio streaming and does not include any audio library to deal with the audio interface or produce input audio streaming. Developers using the toolkit sould build their own applications including the audio library of your preference for your platform.
However, in order to make it easier, we have shared an example project where a minimal sample application is built using RTAudio and a very simple WAV file reader. this example is distributed together with the Visual Studio Project for windows, and can be used as an example to follow. You can find this example here: https://github.com/3DTune-In/3dti_AudioToolkit_Examples
