### ISSUE TITLE
I can't make reverberation work

### ISSUE THREAD

**Issue by Maggie-Jing** [3DTune-In/3dti_AudioToolkit#5]
Hi 3DTI Team,
       As you showed in the example, I've done the audio anechoic spatialization. But when I tryed to follow your example  to add reverb, It generated some noise, i don't know why. I work on the juce platform, there is my code in audio loop:
`	Common::CEarPair<CMonoBuffer<float>> bufferReverb;
	bufferReverb.left.resize(_bufferSize);
	bufferReverb.right.resize(_bufferSize);
 	environment->ProcessVirtualAmbisonicReverb(bufferReverb.left,bufferReverb.right);`
best wish!
maggie

**Comment by areyesl** [comment]
Hi, Maggie. Thank you for using our tool and sorry for taking so long in answering. We are just returning from our holidays :-)

In order to help you, I would need more information. Could you describe your setup? Buffer size? Sample rate? Are you using the BRIR distributed with the example? which HW are you using? And, could you describe the noise or attach a sample? 

(I'm trying to discard a possible performance issue)

Best

Arcadio
