### ISSUE TITLE
Cannot make Reverberation with BRIR working

### ISSUE THREAD

**Issue by EmSavalle** [3DTune-In/3dti_AudioToolkit#9]
Hey 3DTune-In team,
I'm currently trying to use your library to spatialize the sound of a mosquito (for a Brain-Computer Interface experiment).

I need to use the BRIR files to have a good externalisation of the sound but i can't get it to work.
The sound is distorded : it works for .1sec then nothing for .1sec then work for .1sc...

I tried it with the provided example but the same problem is there. (Sample rate 44100Hz, all buffer size with the provided WAV/HRTF/BRIR files)

Is there a way to make it work?
And is the source code for the 3D Tune-In Toolkit Test app available?

Thank you

**Comment by lpicinali** [comment]
Hello!

Thanks for your interest in the Toolkit. Could you please give us some more details, such as: which OS are you using? What is the buffer size you have selected?

Regarding the source code for the Test App, unfortunately we have not released it. Please let us know what you are planning to do which requires the source code, and we'll see what it can be done.

Best regards

Lorenzo

**Comment by EmSavalle** [comment]
Hi,
Thanks for the answer.
I'm currently on Windows 10, is the library optimised for Linux?
And i've tried all buffer size from 256 to 4096, but none of them solved the problem.

I asked for the test app source code, because when I've tried it it was working perfectly with a good externalisation, so I'd like to use it as a base and modify it to fit my needs.

Thank you,
Emile

**Comment by lpicinali** [comment]
Hello Emile,
just to be sure - are you trying to compile the code directly, or you are using the Test App? If the latter, did you download the latest version for Windows?
Finally, are you using it with wired headphones or bluetooth? And are you using it with the onboard inteface or with an external one?
Best regards
Lorenzo

**Comment by EmSavalle** [comment]
I'm compiling the code, i've pull the source code from the 3dti_AudioToolkit_Examples github and compiled it with Visual Studio.

I'm using wired headphones (tried different one to be sure the problems wasn't coming from them).
I'm not sure what you mean by onboard interface.

Emile

**Comment by lpicinali** [comment]
Ok...let us have a look at this and we'll get back to you!

**Comment by EmSavalle** [comment]
Thank you so much for taking the time!

**Comment by areyesl** [comment]
Hi, Emile! 
It sounds like RTAudio is having problems dealing with your audio interface. We have had some issues with that, specially when having several interfaces available. 

We have improved a bit the code of the example to let the user choose between all the available interfaces. In case you have more than one, you can then try with all of them to see if the problem is  in all of them.

Another thing you can try is to check the audio properties of your interface. Go to the sound devices control pannel and check your device properties to ensure in the "advanced" tag that it is set at a sample rate of 44100Hz and the audio improvements by Windows are disabled.

I hope that can solve the problem. In any case, this is an opportunity for us to add a second example which uses Portaudio instead of Rtaudio. We are going to work on that this week and I'll keep you informed in this thread.

Best regards,
Arcadio

**Comment by EmSavalle** [comment]
Hello Arcadio!
Thank you so much for taking the time, especially in this confusing time.

I tried the modifications of the audio properties but it didn't solve the problems.

However, instead of playing directly the sound once it goes throught the audio modification (with HRTFs and BRIRs) I decided to keep those buffers and save them as a WAV file at the end.
And it worked perfectly (great sound resolution and externalisation)!

I'm not sure if it helps but wanted to tell you.
I would still need it to work without that trick though.

Best regards,
Emile

**Comment by areyesl** [comment]
Thanks, Emile,

That supports my idea that we are having troubles with RTAudio. I still think that we should go for Portaudio as a second example, I'll ask you to try once we have it.

Best regards,
Arcadio

**Comment by areyesl** [comment]
Hi, Emile

We have added a second example using PortAudio instead of RTAudio. Could you try?

By the way, we took the opportunity to rearrange the folder structure and therefore, the previous example with RTAudio has changed. Beware of the change we did, as we moved RTAudio lib to a common third party libs folder.

Finally, just to check. You should compile in Release mode. The toolkit processing is quite heavy and Debug mode is not feasible for real time for most computers.

Best regards
Arcadio

**Comment by EmSavalle** [comment]
Hello Arcadio

Thanks for the update.
I followed your instruction for the installation and compiling, but it crashes when I try it, just after it ask for reverb. Any advice on how to make it work?

However, did you changed something to the RTAudio version? It works fine now!

Anyway, if you need me to run some tests, I'd gladly help.

Thank you,
Emile

**Comment by areyesl** [comment]
Hi, Emile,

Good to know that RTAudio works now, but we didn't change anything in the code. Just rearrange the folder structure and tydy up a bit the output folders in the Visual Studio settings. 

Please, make sure that you are compiling in Release mode, not Debug. Could you confirm it?

This can also be related with the crash of the PortAudio version. We have seen that we also have a crash with PortAudio if the the process is too slow and cannot be completed witin a frame time. And this is always the case in Debug mode. This is something to be refined in our example.

Best

Arcadio

**Comment by EmSavalle** [comment]
Hi,

Yes I'm compiling in Release mode, tryied both ways but crashes for both

Emile

**Comment by mariacuevas** [comment]
Hi, Emile,

We think this issue is solved since you made reverberation working with Rtaudio. Please, if you still have any trouble running the portAudio example, open a new issue in that repository (https://github.com/3DTune-In/3dti_AudioToolkit_Examples) and give us some more details about the problem, we will be happy to help you.

Best,
Maria.

**Comment by dgonzalezt** [comment]
Hi, @EmSavalle 

In the last [commit ](https://github.com/3DTune-In/3dti_AudioToolkit_Examples/commit/2ce0c6a8881de9025de38f9d7888b294a51ec482)of the repository, among other things, we've fixed a bug in the portaudio example that may have caused it to crash in your computer. I just wanted to inform you, in case you still need to use the example.

Best, 
Daniel

**Comment by EmSavalle** [comment]
Hi @dgonzalezt,
Thanks for the update, but I'm currently working with the RTAudio version (which has given me great results for my research!).

Thank you!
Emile
